[theme]

# Primary accent for interactive elements
primaryColor = '#FC4E02'

# Background color for the main content area
backgroundColor = '#222222'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2CC561'
# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"